
import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import { UserProvider } from "./context/context"; // Import UserProvider

const inter = Inter({ subsets: ["latin"] });
const Headers = dynamic(() => import("./components/header"), { ssr: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <UserProvider> {/* Wrap the application with UserProvider */}
          <Headers />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
