
import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "./context/context";
import { HeaderProvider } from "./context/headerContext";
import ClientHeader from "./components/ClientHeader"; // Import ClientHeader

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderProvider>
          <UserProvider>
            <ClientHeader /> {/* Use ClientHeader for conditional rendering */}
            {children}
          </UserProvider>
        </HeaderProvider>
      </body>
    </html>
  );
}